/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class */

#ifndef _Included_io_github_noodle1983_Boostrap
#define _Included_io_github_noodle1983_Boostrap
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT int JNICALL Java_com_unity3d_hookplayer_Boostrap_init(JNIEnv *, jclass cls);

JNIEXPORT void JNICALL Java_com_unity3d_hookplayer_Boostrap_setInitPath(JNIEnv *, jclass cls, jstring path);
  
JNIEXPORT int JNICALL Java_com_unity3d_hookplayer_Boostrap_useDataDir(JNIEnv * jenv, jclass cls, jstring data_path, jstring apk_path);

#ifdef __cplusplus
}
#endif
#endif
