/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_noodle1983_Boostrap */

#ifndef _Included_io_github_noodle1983_Boostrap
#define _Included_io_github_noodle1983_Boostrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_noodle1983_Boostrap
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_noodle1983_Boostrap_init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
